# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

flatpak:
  timeout: 1h 30m

include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-appimage.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-windows-mingw64.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-macos-x86-64.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-macos-arm64.yml

xml_lint:
  stage: build
  image: invent-registry.kde.org/sysadmin/ci-images/suse-qt515:latest
  tags:
    - Linux
  script:
    # enable globstar to be able to use ** as recursive wildcard
    - shopt -s globstar
    # exit shell on non-zero exit code
    - set -e 
    # execute xmllint for all xml files
    - for x in **/*.xml; do echo "Processing $x"; xmllint -noout "$x"; done
  rules:
    - changes: [ "**/*.xml" ]
